name: Check Linked Issues
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  check-linked-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Get linked issues
        id: get-issues
        uses: mondeja/pr-linked-issues-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure PR has linked issues
        if: ${{ steps.get-issues.outputs.issues == '' }}
        run: |
          echo "No linked issues found. Please link an issue to this Pull Request."
          exit 1
